# Generated by Django 2.1.3 on 2018-11-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='humidity',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sunlight',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='temperature',
            field=models.CharField(max_length=30),
        ),
    ]
